- frontend/package.json
Linter fixed errors instead of reporting them.
> Fix linting check.

- frontend/package.json
- frontend/src/components/Header.vue
- frontend/src/router/index.js
- frontend/src/views/RouteFormView.vue
- frontend/src/views/RoutesView.vue
Add some routes via form to see routes on this view.
> #35 List of routes view

- frontend/.eslintrc.js
- frontend/src/App.vue
- frontend/src/components/Footer.vue
- frontend/src/components/Header.vue
- frontend/src/components/LoginStatus.vue
- frontend/src/components/Refresh.vue
- frontend/src/components/Status.vue
- frontend/src/scss/base.scss
- frontend/src/views/HomeView.vue
- frontend/src/views/LoginView.vue
- frontend/src/views/RouteFormView.vue
- frontend/src/views/RoutesView.vue
* Added outer container to the page, which makes all sub-pages more consistent
* Added better linting, which makes consistent requirements in regards to layouts [reference](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/html-indent.md)
> cleaned up styles

- Makefile
Fixed indent in Makefile - 2 spaces changed to tab. Fixed api adress fot `test_auth`.
> Fixes in Makefile

- .editorconfig
- Makefile
- docker-compose.yml
- frontend/docker-entrypoint.sh
- frontend/package.json
- frontend/src/store/mutations.js
- pah-fm.conf
1) Add Nginx webserver service.
2) Use Nginx to proxy to Django.
3) Use Nginx to serve built assets.
4) Frontend container builds assets and puts them in shared
volume.
> Fix Docker development tools.

- frontend/docker-entrypoint.sh
- pah-fm.conf
I must have missed something in the first PR.
Additionally, the wrong path was cleaned when building frontend assets.
QA notes:
* `docker-compose stop webserver frontend`
* `docker-compose up webserver frontend`
> Fix nginx not passing URL to SPA.

- frontend/src/main.js
- frontend/src/services/api/cars.js
- frontend/src/store/actions.js
- frontend/src/store/index.js
- frontend/src/store/mutations.js
- frontend/src/translations.json
- frontend/src/views/RouteFormView.vue
- frontend/src/views/RoutesView.vue
- frontend/src/views/services.js
> Add select with cars to route form [fixes #68]

- frontend/src/App.vue
- frontend/src/components/Footer.vue
- frontend/src/components/Status.vue
- frontend/src/main.js
- frontend/src/router/constants.js
- frontend/src/router/index.js
- frontend/src/translations.json
- frontend/src/views/HomeView.vue
Unify routes.
Change URLS:
/route -> /drive
/routes -> /drives
Adds simple 404 page (closes #119)
> Cleanup routes.

- frontend/src/views/RouteFormView.vue
> Set min and max in start/end mileage.

- Makefile
This command:
- stops containers "frontend" and "backend"
- removes containers "frontend" and "backend", including volumes
- rebuilds images for "frontend" and "backend"
> Add make-rebuild command.

- Makefile
- README.md
Move description of Makefile from README to Makefile.
Closes #160 
* Type command `make` into terminal in top level directory of the project. You should see list of available commands with their description.
* Type command `make help` into terminal in top level directory of the project. You should see list of available commands with their description.
* Type command `make checkout BRANCH=master` into terminal in top level directory of the project. It should checkout you to branch master (or any other specified in the command), rebuild containers (frontend and backend), remove database, start all containers, populate the database.
* Take not of number any PR currently open
* Type command `make checkout PR=150` (substitute 150 with the number of the PR from previous step) into terminal in …
> Add command to checkout to branch.

- backend/fleet_management/serializers.py
- frontend/src/store/actions.js
- frontend/src/store/constants.js
- frontend/src/store/helpers.js
- frontend/src/store/modules.js
- frontend/src/translations.json
- frontend/src/views/RouteFormView.vue
- frontend/src/views/services.js
This brings in project to the frontend form, but needs to be updated on backend to store the data
> Added project to form

- frontend/src/translations.json
- frontend/src/views/DriveFormView.vue
- frontend/src/views/services.js
There are still some UA translations missing.
> PAH-170 | add missing translation, new translation file's structure

- Makefile
- frontend/src/translations.json
> Missing translations + misspell

- frontend/src/views/DriveFormView.vue
> Set current date as default.

- Makefile
> [PAH-217] Extend Makefile's help

- backend/fleet_management/models.py
> Bug in Drives repaired

- frontend/src/store/index.js
- frontend/src/translations.json
- frontend/src/utils.js
- frontend/src/views/DrivesView.vue
> add total mileage sum of drives and unsynced drives to drives list

- Makefile
I have fixed some bugs, removed repetitions and gradually improved the targets the Makefile.
Here's the list of changed things:
- right aligned targets in help for nicer looking output
- help: wrapped the line
- rewritten some comments
- replaced short flags with their longer versions for readability
- rewritten repeated lines to separate targets
- fixed bug with incorrect flags used for docker-compose exec
- added variable checking for empty values and help messages for such cases
- reordered most important commands to top
- simplified few lengthy targets
> Improve Makefile - simplify targets, add variable validations and comments

- backend/fleet_management/test_drives.py
It still requires to:
* use factories instead of raw model instances,
* be checked on Travic-CI.
But that's out of the scope of that pull request.
> Fixing tests

- frontend/package-lock.json
- frontend/package.json
- frontend/src/store/index.js
- frontend/src/utils.js
- frontend/src/views/DrivesView.vue
Total mileage for current month for synced and unsynced drives.
> [239] total mileage for current month

- frontend/src/components/NavigationItems.vue
- frontend/src/router/index.js
This PR will disable the link (specifically: disable <a> tag), but I'm happy to modify it to hiding completely if there's need for it (according to the PR https://github.com/CodeForPoznan/pah-fm/issues/263).
> [263] Disable logging off when user is offline

- backend/fleet_management/test_drives.py
Fixing error and warning in tests due to changes in https://github.com/CodeForPoznan/pah-fm/commit/6083c926262ce868b964a117b8129eebd43f31af
> Fixing tests.

- backend/fleet_management/admin.py
CountryField model by default returns country code.
I used dehydrate from import_export to access CountryField @property name which is full country name.
> Add driver country column.

- frontend/src/App.vue
Force change of close button styling
Solves #264
> PAH-264 change close button size and change its position

- pah_behave/pah_behave/features/data/fixtures.sql
Added country value to fixture
> Fixture fix

- backend/fleet_management/admin.py
- backend/fleet_management/models.py
- backend/fleet_management/test_drives.py
- frontend/package-lock.json
> Add sum_mileage to export

- backend/requirements/dev.txt
> [283] Added ipdb and pdbpp.

- backend/fleet_management/serializers.py
> Added public RSA to Passengerserializer

- backend/fleet_management/admin.py
- backend/fleet_management/models.py
I'm adding `project__title` and `passenger` to the exported columns and also cleaning the code a bit.
> Add new columns in export

- backend/fleet_management/serializers.py
> [316] Expose rsa fields in UserSerializer

- backend/fleet_management/serializers.py
Closes #386.
Open chrome dev tools, send drive via form, right-click on the Network tab on the POST request.
Select copy as cURL and paste it into terminal.
Change ids to some high numbers and check that the error is reported instead of HTTP 500.
> [386] Validate IDs in serializer, check if the objects actually exist

- backend/fleet_management/serializers.py
- frontend/src/views/DriveFormView.vue
- frontend/src/views/DrivesView.vue
Resolves #319. This code adds color bar as an indication for drives which were verified.
> [319] Verify drives on frontend

- frontend/src/store/actions.js
- frontend/src/store/constants.js
- frontend/src/store/index.js
- frontend/src/store/mutations.js
- frontend/src/views/PassengerSubmitView.vue
- frontend/src/views/PassengerView.vue
> [410] sign drive checksum in passengers view

- frontend/src/components/SignatureInput.vue
- frontend/src/views/DriveFormView.vue
- frontend/src/views/PassengerView.vue
> 425 passenger input type

- backend/fleet_management/tests/test_auth_token.py
- backend/pah_fm/urls.py
Solves https://github.com/CodeForPoznan/pah-fm/issues/416
> 416 Add new tests.

- backend/fleet_management/admin.py
- backend/requirements/base.txt
Closes #457 
I'm bumping the package as well, as it fixes the encoding in HTML export, which is nice :)
> [457] Bump import-export, export Drive.is_verified

- backend/fleet_management/admin.py
- backend/fleet_management/models.py
Closes #448
Closes #447 
Closes #456
> [448] Move Admin classes back to Admin, introduce dynamic CountryFilter

- backend/pah_fm/static/css/admin.css
> [465] Change color of breadcrumbs to white, highlight options in filters

- Makefile
- frontend/.eslintrc.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/tests/services/splitCamelCase.test.js
> Add frontend testing setup

- .travis.yml
> Run test in travis

- frontend/src/services/lang.js
- frontend/src/translations.json
> [483] Add Somali translation

- frontend/src/views/DriveFormView.vue
> Remove paragraph with project id

- frontend/src/store/modules/data/index.js
- frontend/src/tests/store/modules/data.test.js
That looked way more complex than it is :laughing: 
This will fix #514 and #513
> [514] Fix disappearing values in form

- deploy.sh
https://travis-ci.com/github/CodeForPoznan/pah-fm/builds/173329939 Line:1781
```
upload failed: ./lambda.zip to s3://codeforpoznan-lambdas/dev_pah_fm.zip An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Access Denied
An error occurred (AccessDeniedException) when calling the UpdateFunctionCode operation: Your access has been denied by S3, please make sure your request credentials have permission to GetObject for codeforpoznan-lambdas/dev_pah_fm.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied
An error occurred (AccessDeniedException) when calling the UpdateFunctionCode operation: Your access has been denied by S3, please make sure your request credentials have permission to GetObject for codeforpoznan-lambdas/dev_pah_fm.zip. S3 Error …
```
> [226] Change lambda zip names according to infra code

- LICENSE
Solves #375 
Please review and approve.
> [375] Add license file

- frontend/src/views/DrivesView.vue
> Passenger in drives view

- backend/fleet_management/tests/test_passengers.py
I've missed that file somehow...
> Format missing test_passengers.py with black

- backend/fleet_management/api.py
> Limit amount of records shown to Driver in Drives View

- frontend/src/store/modules/http/actions.js
- frontend/src/store/modules/http/state.js
- frontend/src/tests/store/modules/http.test.js
> Fix login error, await for promises

- frontend/src/views/DriveFormView.vue
> PAH-536 add different class for invalid select field

- frontend-react/public/index.html
- frontend-react/public/manifest.json
Just a quick PR, favicons are not displayed correctly and this PR fixes it.
> Fix displaying of favicons

- backend/pah_fm/settings.py
- docker-compose.yml
YES! finally :)
turns out the CSRF setting doesn't like a port number in it's name.
> Fix CSRF in django admin
